// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz0kGVYKUb65x89ZVt8LBddO7ExJ_a5b0',
    appId: '1:792319468494:web:f2f11c5e647b8b18e1019f',
    messagingSenderId: '792319468494',
    projectId: 'cantos-1651f',
    authDomain: 'cantos-1651f.firebaseapp.com',
    storageBucket: 'cantos-1651f.appspot.com',
    measurementId: 'G-H72J1PGQZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3gEjqBqbJFjbVUEDX5NmFovhTW2Yml_U',
    appId: '1:792319468494:android:9ef7d4a0882e4d8ce1019f',
    messagingSenderId: '792319468494',
    projectId: 'cantos-1651f',
    storageBucket: 'cantos-1651f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATuYX029M4AOonT3Czx8FBYou6wDHcjAY',
    appId: '1:792319468494:ios:d2c072e8fe76c5d1e1019f',
    messagingSenderId: '792319468494',
    projectId: 'cantos-1651f',
    storageBucket: 'cantos-1651f.appspot.com',
    iosBundleId: 'com.pacosotelo.cantosf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATuYX029M4AOonT3Czx8FBYou6wDHcjAY',
    appId: '1:792319468494:ios:e5efd450566a8029e1019f',
    messagingSenderId: '792319468494',
    projectId: 'cantos-1651f',
    storageBucket: 'cantos-1651f.appspot.com',
    iosBundleId: 'com.pacosotelo.cantosf.RunnerTests',
  );
}
